trigger:
- main

variables:
  imageName: 'taskmanager-app'
  containerRegistry: 'myacrname.azurecr.io'
  tag: '$(Build.BuildId)'

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'Default'   # 👈 KEY CHANGE
    steps:

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'shoppingacr123'
        tags: |
          $(tag)
          latest


- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      name: 'Default'   # 👈 SAME HERE (optional but common)
    steps:

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(05d41934-234a-4887-a212-e032ae353899)'
        appName: 'taskmanager-app'
        containers: '$(containerRegistry)/$(imageName):$(tag)'