# File: azure-pipelines.yml
trigger:
- main  # Replace with your branch

variables:
  imageTag: '22'  # You can make this dynamic later, e.g., $(Build.BuildId)

stages:
- stage: BuildPushDeploy
  displayName: Build, Push Docker Image & Deploy
  jobs:
  - job: BuildAndPush
    displayName: Build & Push Docker Image to ACR
    pool:
      name: 'Default'  # Replace with the name of your self-hosted agent

    steps:
    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: 'Azure subscription 1(05d41934-234a-4887-a212-e032ae353899)'  # Azure DevOps service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure CLI ready"

    - task: Docker@2
      displayName: 'Build and Push Docker image to ACR'
      inputs:
        containerRegistry: 'shoppingacr123'  # Use the ACR service connection name
        repository: 'borozcoshoppingmicroservices'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(imageTag)'

  - job: Deploy
    displayName: Deploy Docker Image to Azure Web App
    dependsOn: BuildAndPush
    pool:
      name: 'Default'  # Self-hosted agent for deployment
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Docker Image to Web App'
      inputs:
       azureSubscription: 'Azure subscription 1(05d41934-234a-4887-a212-e032ae353899)'
       appName: 'taskmanager-app'
       containers: |
         shoppingacr123.azurecr.io/borozcoshoppingmicroservices:22
